# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

modification_loc <- function(inx_name, K, mx_k) {
    .Call(`_GENESISasian_modification_loc`, inx_name, K, mx_k)
}

cpnorm <- function(x) {
    .Call(`_GENESISasian_cpnorm`, x)
}

sumfactorial <- function(n) {
    .Call(`_GENESISasian_sumfactorial`, n)
}

sumfactorial_rev <- function(n, k0) {
    .Call(`_GENESISasian_sumfactorial_rev`, n, k0)
}

cdnorm <- function(x, mean, sd, loglog) {
    .Call(`_GENESISasian_cdnorm`, x, mean, sd, loglog)
}

cdbinom <- function(k, size, prob, loglog) {
    .Call(`_GENESISasian_cdbinom`, k, size, prob, loglog)
}

cdmultinom3 <- function(k0, k1, k2, prob, loglog) {
    .Call(`_GENESISasian_cdmultinom3`, k0, k1, k2, prob, loglog)
}

loglikelihood <- function(par, betahat, varbetahat, ldscore, c0, Nstar, num_threads) {
    .Call(`_GENESISasian_loglikelihood`, par, betahat, varbetahat, ldscore, c0, Nstar, num_threads)
}

weight <- function(par, betahat, varbetahat, ldscore, c0, Nstar, num_threads) {
    .Call(`_GENESISasian_weight`, par, betahat, varbetahat, ldscore, c0, Nstar, num_threads)
}

weight_loglikelihood <- function(par, betahat, varbetahat, ldscore, c0, Nstar, num_threads) {
    .Call(`_GENESISasian_weight_loglikelihood`, par, betahat, varbetahat, ldscore, c0, Nstar, num_threads)
}

update_pi1 <- function(w, Nstar, num_threads) {
    .Call(`_GENESISasian_update_pi1`, w, Nstar, num_threads)
}

onestep_varcomponent <- function(varcomponent, w, betahat, varbetahat, ldscore, Nstar, num_threads) {
    .Call(`_GENESISasian_onestep_varcomponent`, varcomponent, w, betahat, varbetahat, ldscore, Nstar, num_threads)
}

EM_func <- function(par_start, betahat, varbetahat, ldscore, Nstar, M, c0, eps1, eps2, eps3, eps, Meps, steps, num_threads, print, printfreq, stratification) {
    .Call(`_GENESISasian_EM_func`, par_start, betahat, varbetahat, ldscore, Nstar, M, c0, eps1, eps2, eps3, eps, Meps, steps, num_threads, print, printfreq, stratification)
}

Sk <- function(par, betahatk, varbetahatk, ldscorek, c0, Nstark) {
    .Call(`_GENESISasian_Sk`, par, betahatk, varbetahatk, ldscorek, c0, Nstark)
}

Ik <- function(par, betahatk, varbetahatk, ldscorek, c0, Nstark) {
    .Call(`_GENESISasian_Ik`, par, betahatk, varbetahatk, ldscorek, c0, Nstark)
}

S <- function(par, betahat, varbetahat, ldscore, c0, Nstar, num_threads) {
    .Call(`_GENESISasian_S`, par, betahat, varbetahat, ldscore, c0, Nstar, num_threads)
}

SS <- function(par, betahat, varbetahat, ldscore, c0, Nstar, num_threads) {
    .Call(`_GENESISasian_SS`, par, betahat, varbetahat, ldscore, c0, Nstar, num_threads)
}

I <- function(par, betahat, varbetahat, ldscore, c0, Nstar, num_threads) {
    .Call(`_GENESISasian_I`, par, betahat, varbetahat, ldscore, c0, Nstar, num_threads)
}

mixture_components_marginal <- function(par, ldscore, c0, Nstar, num_threads) {
    .Call(`_GENESISasian_mixture_components_marginal`, par, ldscore, c0, Nstar, num_threads)
}

loglikelihood3 <- function(par, betahat, varbetahat, ldscore, c0, Nstar, num_threads) {
    .Call(`_GENESISasian_loglikelihood3`, par, betahat, varbetahat, ldscore, c0, Nstar, num_threads)
}

weight3 <- function(par, betahat, varbetahat, ldscore, c0, Nstar, num_threads) {
    .Call(`_GENESISasian_weight3`, par, betahat, varbetahat, ldscore, c0, Nstar, num_threads)
}

weight_loglikelihood3 <- function(par, betahat, varbetahat, ldscore, c0, Nstar, num_threads) {
    .Call(`_GENESISasian_weight_loglikelihood3`, par, betahat, varbetahat, ldscore, c0, Nstar, num_threads)
}

update_p3 <- function(w, Nstar, num_threads) {
    .Call(`_GENESISasian_update_p3`, w, Nstar, num_threads)
}

onestep_varcomponent3 <- function(varcomponent, w, betahat, varbetahat, ldscore, Nstar, num_threads) {
    .Call(`_GENESISasian_onestep_varcomponent3`, varcomponent, w, betahat, varbetahat, ldscore, Nstar, num_threads)
}

EM_func3 <- function(par_start, lower_pi, upper_pi, betahat, varbetahat, ldscore, Nstar, M, c0, eps1, eps2, eps3, eps4, eps5, eps, Meps, steps, num_threads, print, printfreq, stratification) {
    .Call(`_GENESISasian_EM_func3`, par_start, lower_pi, upper_pi, betahat, varbetahat, ldscore, Nstar, M, c0, eps1, eps2, eps3, eps4, eps5, eps, Meps, steps, num_threads, print, printfreq, stratification)
}

Sk3 <- function(par, betahatk, varbetahatk, ldscorek, c0, Nstark) {
    .Call(`_GENESISasian_Sk3`, par, betahatk, varbetahatk, ldscorek, c0, Nstark)
}

Ik3 <- function(par, betahatk, varbetahatk, ldscorek, c0, Nstark) {
    .Call(`_GENESISasian_Ik3`, par, betahatk, varbetahatk, ldscorek, c0, Nstark)
}

S3 <- function(par, betahat, varbetahat, ldscore, c0, Nstar) {
    .Call(`_GENESISasian_S3`, par, betahat, varbetahat, ldscore, c0, Nstar)
}

SS3 <- function(par, betahat, varbetahat, ldscore, c0, Nstar, num_threads) {
    .Call(`_GENESISasian_SS3`, par, betahat, varbetahat, ldscore, c0, Nstar, num_threads)
}

I3 <- function(par, betahat, varbetahat, ldscore, c0, Nstar, num_threads) {
    .Call(`_GENESISasian_I3`, par, betahat, varbetahat, ldscore, c0, Nstar, num_threads)
}

mixture_3components_marginal <- function(par, ldscore, c0, Nstar, num_threads) {
    .Call(`_GENESISasian_mixture_3components_marginal`, par, ldscore, c0, Nstar, num_threads)
}

